version: '3.4'

services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes:
      - ./docker-volumes/redis-data:/var/lib/redis
      - ./docker-volumes/redis.conf:/usr/local/etc/redis/redis.conf
  frontend:
    container_name: bananarama-voting-bananza-frontend
    image: mhart/alpine-node:16
    volumes:
      - ./frontend:/app/frontend
    ports:
      - 3000:3000
    working_dir: /app/frontend
    command: [ "yarn", "run", "sd:fe" ]
  backend:
    container_name: bananarama-voting-bananza-backend
    image: mhart/alpine-node:16
    volumes:
      - ./backend:/app/backend
    ports:
      - 8080:8080
      - 4000:4000
    working_dir: /app/backend
    command: [ "yarn", "run", "sd:be" ]
    environment:
      - NODE_ENV=local
